export interface Department {
  num: string;   // "33"
  name: string;  // "Gironde"
  slug: string;  // "gironde"
  city: string;  // "Bordeaux" (chef-lieu)
}

export const DEPARTMENTS: Department[] = [
  { num: "01", name: "Ain", slug: "ain", city: "Bourg-en-Bresse" },
  { num: "02", name: "Aisne", slug: "aisne", city: "Laon" },
  { num: "03", name: "Allier", slug: "allier", city: "Moulins" },
  { num: "04", name: "Alpes-de-Haute-Provence", slug: "alpes-de-haute-provence", city: "Digne-les-Bains" },
  { num: "05", name: "Hautes-Alpes", slug: "hautes-alpes", city: "Gap" },
  { num: "06", name: "Alpes-Maritimes", slug: "alpes-maritimes", city: "Nice" },
  { num: "07", name: "Ardèche", slug: "ardeche", city: "Privas" },
  { num: "08", name: "Ardennes", slug: "ardennes", city: "Charleville-Mézières" },
  { num: "09", name: "Ariège", slug: "ariege", city: "Foix" },
  { num: "10", name: "Aube", slug: "aube", city: "Troyes" },
  { num: "11", name: "Aude", slug: "aude", city: "Carcassonne" },
  { num: "12", name: "Aveyron", slug: "aveyron", city: "Rodez" },
  { num: "13", name: "Bouches-du-Rhône", slug: "bouches-du-rhone", city: "Marseille" },
  { num: "14", name: "Calvados", slug: "calvados", city: "Caen" },
  { num: "15", name: "Cantal", slug: "cantal", city: "Aurillac" },
  { num: "16", name: "Charente", slug: "charente", city: "Angoulême" },
  { num: "17", name: "Charente-Maritime", slug: "charente-maritime", city: "La Rochelle" },
  { num: "18", name: "Cher", slug: "cher", city: "Bourges" },
  { num: "19", name: "Corrèze", slug: "correze", city: "Tulle" },
  { num: "2A", name: "Corse-du-Sud", slug: "corse-du-sud", city: "Ajaccio" },
  { num: "2B", name: "Haute-Corse", slug: "haute-corse", city: "Bastia" },
  { num: "21", name: "Côte-d'Or", slug: "cote-dor", city: "Dijon" },
  { num: "22", name: "Côtes-d'Armor", slug: "cotes-darmor", city: "Saint-Brieuc" },
  { num: "23", name: "Creuse", slug: "creuse", city: "Guéret" },
  { num: "24", name: "Dordogne", slug: "dordogne", city: "Périgueux" },
  { num: "25", name: "Doubs", slug: "doubs", city: "Besançon" },
  { num: "26", name: "Drôme", slug: "drome", city: "Valence" },
  { num: "27", name: "Eure", slug: "eure", city: "Évreux" },
  { num: "28", name: "Eure-et-Loir", slug: "eure-et-loir", city: "Chartres" },
  { num: "29", name: "Finistère", slug: "finistere", city: "Quimper" },
  { num: "30", name: "Gard", slug: "gard", city: "Nîmes" },
  { num: "31", name: "Haute-Garonne", slug: "haute-garonne", city: "Toulouse" },
  { num: "32", name: "Gers", slug: "gers", city: "Auch" },
  { num: "33", name: "Gironde", slug: "gironde", city: "Bordeaux" },
  { num: "34", name: "Hérault", slug: "herault", city: "Montpellier" },
  { num: "35", name: "Ille-et-Vilaine", slug: "ille-et-vilaine", city: "Rennes" },
  { num: "36", name: "Indre", slug: "indre", city: "Châteauroux" },
  { num: "37", name: "Indre-et-Loire", slug: "indre-et-loire", city: "Tours" },
  { num: "38", name: "Isère", slug: "isere", city: "Grenoble" },
  { num: "39", name: "Jura", slug: "jura", city: "Lons-le-Saunier" },
  { num: "40", name: "Landes", slug: "landes", city: "Mont-de-Marsan" },
  { num: "41", name: "Loir-et-Cher", slug: "loir-et-cher", city: "Blois" },
  { num: "42", name: "Loire", slug: "loire", city: "Saint-Étienne" },
  { num: "43", name: "Haute-Loire", slug: "haute-loire", city: "Le Puy-en-Velay" },
  { num: "44", name: "Loire-Atlantique", slug: "loire-atlantique", city: "Nantes" },
  { num: "45", name: "Loiret", slug: "loiret", city: "Orléans" },
  { num: "46", name: "Lot", slug: "lot", city: "Cahors" },
  { num: "47", name: "Lot-et-Garonne", slug: "lot-et-garonne", city: "Agen" },
  { num: "48", name: "Lozère", slug: "lozere", city: "Mende" },
  { num: "49", name: "Maine-et-Loire", slug: "maine-et-loire", city: "Angers" },
  { num: "50", name: "Manche", slug: "manche", city: "Saint-Lô" },
  { num: "51", name: "Marne", slug: "marne", city: "Châlons-en-Champagne" },
  { num: "52", name: "Haute-Marne", slug: "haute-marne", city: "Chaumont" },
  { num: "53", name: "Mayenne", slug: "mayenne", city: "Laval" },
  { num: "54", name: "Meurthe-et-Moselle", slug: "meurthe-et-moselle", city: "Nancy" },
  { num: "55", name: "Meuse", slug: "meuse", city: "Bar-le-Duc" },
  { num: "56", name: "Morbihan", slug: "morbihan", city: "Vannes" },
  { num: "57", name: "Moselle", slug: "moselle", city: "Metz" },
  { num: "58", name: "Nièvre", slug: "nievre", city: "Nevers" },
  { num: "59", name: "Nord", slug: "nord", city: "Lille" },
  { num: "60", name: "Oise", slug: "oise", city: "Beauvais" },
  { num: "61", name: "Orne", slug: "orne", city: "Alençon" },
  { num: "62", name: "Pas-de-Calais", slug: "pas-de-calais", city: "Arras" },
  { num: "63", name: "Puy-de-Dôme", slug: "puy-de-dome", city: "Clermont-Ferrand" },
  { num: "64", name: "Pyrénées-Atlantiques", slug: "pyrenees-atlantiques", city: "Pau" },
  { num: "65", name: "Hautes-Pyrénées", slug: "hautes-pyrenees", city: "Tarbes" },
  { num: "66", name: "Pyrénées-Orientales", slug: "pyrenees-orientales", city: "Perpignan" },
  { num: "67", name: "Bas-Rhin", slug: "bas-rhin", city: "Strasbourg" },
  { num: "68", name: "Haut-Rhin", slug: "haut-rhin", city: "Colmar" },
  { num: "69", name: "Rhône", slug: "rhone", city: "Lyon" },
  { num: "70", name: "Haute-Saône", slug: "haute-saone", city: "Vesoul" },
  { num: "71", name: "Saône-et-Loire", slug: "saone-et-loire", city: "Mâcon" },
  { num: "72", name: "Sarthe", slug: "sarthe", city: "Le Mans" },
  { num: "73", name: "Savoie", slug: "savoie", city: "Chambéry" },
  { num: "74", name: "Haute-Savoie", slug: "haute-savoie", city: "Annecy" },
  { num: "75", name: "Paris", slug: "paris", city: "Paris" },
  { num: "76", name: "Seine-Maritime", slug: "seine-maritime", city: "Rouen" },
  { num: "77", name: "Seine-et-Marne", slug: "seine-et-marne", city: "Melun" },
  { num: "78", name: "Yvelines", slug: "yvelines", city: "Versailles" },
  { num: "79", name: "Deux-Sèvres", slug: "deux-sevres", city: "Niort" },
  { num: "80", name: "Somme", slug: "somme", city: "Amiens" },
  { num: "81", name: "Tarn", slug: "tarn", city: "Albi" },
  { num: "82", name: "Tarn-et-Garonne", slug: "tarn-et-garonne", city: "Montauban" },
  { num: "83", name: "Var", slug: "var", city: "Toulon" },
  { num: "84", name: "Vaucluse", slug: "vaucluse", city: "Avignon" },
  { num: "85", name: "Vendée", slug: "vendee", city: "La Roche-sur-Yon" },
  { num: "86", name: "Vienne", slug: "vienne", city: "Poitiers" },
  { num: "87", name: "Haute-Vienne", slug: "haute-vienne", city: "Limoges" },
  { num: "88", name: "Vosges", slug: "vosges", city: "Épinal" },
  { num: "89", name: "Yonne", slug: "yonne", city: "Auxerre" },
  { num: "90", name: "Territoire de Belfort", slug: "territoire-de-belfort", city: "Belfort" },
  { num: "91", name: "Essonne", slug: "essonne", city: "Évry-Courcouronnes" },
  { num: "92", name: "Hauts-de-Seine", slug: "hauts-de-seine", city: "Nanterre" },
  { num: "93", name: "Seine-Saint-Denis", slug: "seine-saint-denis", city: "Bobigny" },
  { num: "94", name: "Val-de-Marne", slug: "val-de-marne", city: "Créteil" },
  { num: "95", name: "Val-d'Oise", slug: "val-doise", city: "Cergy" },
];

export function getDeptBySlug(slug: string): Department | undefined {
  return DEPARTMENTS.find((d) => d.slug === slug);
}
